"""Centralized tunable parameters, all overridable via environment variables."""

from __future__ import annotations

import os


def _int(key: str, default: int) -> int:
    return int(os.getenv(key, str(default)))


class Defaults:
    TURN_TIMEOUT_SECONDS = _int("COLEARN_TURN_TIMEOUT", 120)
    RUNTIME_MAX_RETRIEVAL_CHARS = _int("COLEARN_RUNTIME_MAX_RETRIEVAL", 4000)
    RUNTIME_MAX_CHUNK_CHARS = _int("COLEARN_RUNTIME_MAX_CHUNK", 1200)
    RUNTIME_MAX_USER_MESSAGE_CHARS = _int("COLEARN_RUNTIME_MAX_USER_MESSAGE", 3000)
    PRODUCT_MAX_SUMMARY_CHARS = _int("COLEARN_PRODUCT_MAX_SUMMARY", 240)
    PRODUCT_MAX_CONTINUATION_CHARS = _int("COLEARN_PRODUCT_MAX_CONTINUATION", 180)
    SESSION_AUTOCOMPACT_MAX_MESSAGES = _int("COLEARN_SESSION_AUTOCOMPACT_MAX", 24)
    SESSION_AUTOCOMPACT_KEEP_TAIL = _int("COLEARN_SESSION_AUTOCOMPACT_TAIL", 12)
    DREAM_CONSOLIDATION_EVENT_INTERVAL = _int("COLEARN_DREAM_INTERVAL", 20)
    BOARD_DERIVATION_EVENT_INTERVAL = _int("COLEARN_BOARD_INTERVAL", 5)
    BOARD_DERIVATION_MAX_EVENTS = _int("COLEARN_BOARD_MAX_EVENTS", 30)
    PROMPT_SUPPORT_MAX_ITEMS = _int("COLEARN_PROMPT_SUPPORT_MAX", 4)
    RETRIEVAL_TOP_K = _int("COLEARN_RETRIEVAL_TOP_K", 5)
    RETRIEVAL_CACHE_TTL_SECONDS = _int("COLEARN_RETRIEVAL_CACHE_TTL", 300)
    RETRIEVAL_CACHE_MAX_ENTRIES = _int("COLEARN_RETRIEVAL_CACHE_MAX", 128)
    MEMORY_STORE_MAX_EVENTS = _int("COLEARN_MEMORY_MAX_EVENTS", 500)
    SESSION_MAX_IDLE_SECONDS = _int("COLEARN_SESSION_MAX_IDLE", 3600)
